development:
  merchant_email: jatin.merchant2@vinsol.com
  redirect_url: https://www.sandbox.paypal.com/cgi-bin/webscr?

test:
  merchant_email: jatin.merchant2@vinsol.com
  redirect_url: https://www.sandbox.paypal.com/cgi-bin/webscr?

production:
  merchant_email: xyz@abc.com
  redirect_url: https://www.paypal.com/cgi-bin/webscr?
